### PR TITLE
Add phrase: I wish I was/were vegan

### PR DESCRIPTION
**Pull request by squeek502**
Just going to keep submitting random pull requests as I think of more possible phrases. :smile:

### CODE REVIEW

**Comment by joriskcf** [comment]
I'll get to work on a bot that automatically accepts @squeek502's PRs and tweets about it.

**Comment by plorry** [comment]
@squeek502 I've added you as a collaborator. I'll put up PRs for my own proposed changes from now on too, so I can get feedback before deploying

**Comment by squeek502** [comment]
Sounds good. :+1:

**Comment by plorry** [comment]
@joriskcf but who will accept PRs for _that_ bot?

**Pull request merged**
